### ISSUE TITLE
Power supply

### ISSUE THREAD

**Issue by BertilJ** [MortenVinding/Robomow-ESP32#5]
This looks great and I can't wait to try it out. Still some snow where I'm at, so it's a month before it's time to let it out again. :)

But meanwhile, what voltage converters are you using to power the ESP? I had a webcam connected earlier and the voltage converter I was using was messing up with the built in BMS on the Robomow, so it was basically balancing the battery after each charge for some hours before going out again. As soon as I disconnected the voltage converter, the behaviour went back to the usual.

So need to get a better one that doesn't mess with the BMS. Suggestions?

**Comment by MortenVinding** [comment]
> But meanwhile, what voltage converters are you using to power the ESP?

I just used what I already had at hand :)
This one in the 3.3v version (no reason to convert to 5v and then to 3.3v on the ESP board also 😊):
https://a.aliexpress.com/_EvsL88B

Right now it's connected to the GSM DB9 plug in the mower, but I found out it's powered down when the mower is charging, so I think I will find a way to hook it directly to the battery.

Don't think it interferes with the BMS, but hasn't really used the robot yet this season (doing some remodelling of the garden right now).

**Comment by MortenVinding** [comment]
Look in the image folder, there is pictures of how I build it in to the battery :)

**Comment by wimmme** [comment]
Hi, sorry to reopen this, I just started with this project. i have a RC304 that I always wanted to be able to control remotely.
The ESP  and flashing part works, thanks for the software and the English translation.  Now I have to build the ESP into the Robomow.
What i was wondering, the wires that I need to use to attach to the Step Down converter, so the 25.6V DC, are those the slightly thicker red and black cables in the cable bundle ? For the black cable I see only one, the red are 2 of them. Can i use just one of these then ? Thanks in advance.
