### ISSUE TITLE
Is this also compatible with the B+D Mower?

### ISSUE THREAD

**Issue by JochenV1976** [MortenVinding/Robomow-ESP32#6]
Is this also compatible with the B+D Mower?
And if so, how can I find the motherboard Serial Number? 

I can't connect to the B+D robot mower login (https://robotmower.blackanddecker.eu/#!/en/login) because the robot model is not compatible. Of course it doesn't work on the robomow site either :(

Any ideas?

**Comment by MortenVinding** [comment]
> Is this also compatible with the B+D Mower? And if so, how can I find the motherboard Serial Number?
.
.
.
> Any ideas?

Sorry I have no idea.
Looks like the B+D robots is rebranded Robomow RT models, but I don't know if they use the same bluetooth protocol.
MB serial number can be obtained for the other models with Robomow windows tool and a standard serial DB9 cable, but I don't know if that also works with the RT's
