### ISSUE TITLE
HomeAssistant integration

### ISSUE THREAD

**Issue by filepgeregly** [MortenVinding/Robomow-ESP32#7]
I'm trying to integrate it to HA, but i get constanty the following errors:

```
Configuration errors
Invalid config for 'homeassistant' at robomow.yaml, line 1: 'switch' is an invalid option for 'homeassistant', check: customize->switch
Invalid config for 'homeassistant' at robomow.yaml, line 22: 'rest_command' is an invalid option for 'homeassistant', check: customize->rest_command
Invalid config for 'homeassistant' at robomow.yaml, line 40: 'sensor' is an invalid option for 'homeassistant', check: customize->sensor
```

What is the problem? Is that YAML is valid, for the current HA version?

**Comment by torroa** [comment]
Yeah, I could not get it to work without including the sensors, switches and rest_commands directly in configuration.yaml. You also need several scripts, like thise one:

> alias: Robomow Flaeche
sequence:
  - service: rest_command.robomowflaeche
    metadata: {}
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: homeassistant.update_entity
    metadata: {}
    data: {}
    target:
      entity_id: sensor.robomow
mode: single
icon: mdi:grass

**Comment by MortenVinding** [comment]
> I'm trying to integrate it to HA, but i get constanty the following errors:
> 

Sorry I made a mistake.
Have updated the README now. This is what it should have been:

=========================================
Copy robomow.yaml to config/packages/robomow.yaml
<sub>make dir config/packages if non existent</sub>

Add this to config/configuration.yaml
```
homeassistant:  
  packages: !include_dir_named packages
```

**Comment by filepgeregly** [comment]
Thanks, it's working now!
